// source: google/events/cloud/storage/v1/data.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.google.events.cloud.storage.v1.StorageObjectData', null, global);
goog.exportSymbol('proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.events.cloud.storage.v1.StorageObjectData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.events.cloud.storage.v1.StorageObjectData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.events.cloud.storage.v1.StorageObjectData.displayName = 'proto.google.events.cloud.storage.v1.StorageObjectData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.displayName = 'proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.toObject = function(opt_includeInstance) {
  return proto.google.events.cloud.storage.v1.StorageObjectData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.events.cloud.storage.v1.StorageObjectData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.storage.v1.StorageObjectData.toObject = function(includeInstance, msg) {
  var f, obj = {
    contentEncoding: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contentDisposition: jspb.Message.getFieldWithDefault(msg, 2, ""),
    cacheControl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    contentLanguage: jspb.Message.getFieldWithDefault(msg, 5, ""),
    metageneration: jspb.Message.getFieldWithDefault(msg, 6, 0),
    timeDeleted: (f = msg.getTimeDeleted()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    contentType: jspb.Message.getFieldWithDefault(msg, 8, ""),
    size: jspb.Message.getFieldWithDefault(msg, 9, 0),
    timeCreated: (f = msg.getTimeCreated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    crc32c: jspb.Message.getFieldWithDefault(msg, 11, ""),
    componentCount: jspb.Message.getFieldWithDefault(msg, 12, 0),
    md5Hash: jspb.Message.getFieldWithDefault(msg, 13, ""),
    etag: jspb.Message.getFieldWithDefault(msg, 14, ""),
    updated: (f = msg.getUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    storageClass: jspb.Message.getFieldWithDefault(msg, 16, ""),
    kmsKeyName: jspb.Message.getFieldWithDefault(msg, 17, ""),
    timeStorageClassUpdated: (f = msg.getTimeStorageClassUpdated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    temporaryHold: jspb.Message.getBooleanFieldWithDefault(msg, 19, false),
    retentionExpirationTime: (f = msg.getRetentionExpirationTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    metadataMap: (f = msg.getMetadataMap()) ? f.toObject(includeInstance, undefined) : [],
    eventBasedHold: jspb.Message.getBooleanFieldWithDefault(msg, 29, false),
    name: jspb.Message.getFieldWithDefault(msg, 23, ""),
    id: jspb.Message.getFieldWithDefault(msg, 24, ""),
    bucket: jspb.Message.getFieldWithDefault(msg, 25, ""),
    generation: jspb.Message.getFieldWithDefault(msg, 26, 0),
    customerEncryption: (f = msg.getCustomerEncryption()) && proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.toObject(includeInstance, f),
    mediaLink: jspb.Message.getFieldWithDefault(msg, 100, ""),
    selfLink: jspb.Message.getFieldWithDefault(msg, 101, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.events.cloud.storage.v1.StorageObjectData;
  return proto.google.events.cloud.storage.v1.StorageObjectData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.events.cloud.storage.v1.StorageObjectData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentEncoding(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentDisposition(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCacheControl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentLanguage(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMetageneration(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeDeleted(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setContentType(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSize(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeCreated(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setCrc32c(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setComponentCount(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setMd5Hash(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setEtag(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdated(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setStorageClass(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setKmsKeyName(value);
      break;
    case 18:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeStorageClassUpdated(value);
      break;
    case 19:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTemporaryHold(value);
      break;
    case 20:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setRetentionExpirationTime(value);
      break;
    case 21:
      var value = msg.getMetadataMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 29:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEventBasedHold(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 25:
      var value = /** @type {string} */ (reader.readString());
      msg.setBucket(value);
      break;
    case 26:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setGeneration(value);
      break;
    case 28:
      var value = new proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption;
      reader.readMessage(value,proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.deserializeBinaryFromReader);
      msg.setCustomerEncryption(value);
      break;
    case 100:
      var value = /** @type {string} */ (reader.readString());
      msg.setMediaLink(value);
      break;
    case 101:
      var value = /** @type {string} */ (reader.readString());
      msg.setSelfLink(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.events.cloud.storage.v1.StorageObjectData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.events.cloud.storage.v1.StorageObjectData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.storage.v1.StorageObjectData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContentEncoding();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContentDisposition();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCacheControl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getContentLanguage();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMetageneration();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getTimeDeleted();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getContentType();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSize();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getTimeCreated();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCrc32c();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getComponentCount();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getMd5Hash();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getEtag();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getUpdated();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getStorageClass();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getKmsKeyName();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getTimeStorageClassUpdated();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getTemporaryHold();
  if (f) {
    writer.writeBool(
      19,
      f
    );
  }
  f = message.getRetentionExpirationTime();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMetadataMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(21, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getEventBasedHold();
  if (f) {
    writer.writeBool(
      29,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getBucket();
  if (f.length > 0) {
    writer.writeString(
      25,
      f
    );
  }
  f = message.getGeneration();
  if (f !== 0) {
    writer.writeInt64(
      26,
      f
    );
  }
  f = message.getCustomerEncryption();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.serializeBinaryToWriter
    );
  }
  f = message.getMediaLink();
  if (f.length > 0) {
    writer.writeString(
      100,
      f
    );
  }
  f = message.getSelfLink();
  if (f.length > 0) {
    writer.writeString(
      101,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.prototype.toObject = function(opt_includeInstance) {
  return proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.toObject = function(includeInstance, msg) {
  var f, obj = {
    encryptionAlgorithm: jspb.Message.getFieldWithDefault(msg, 1, ""),
    keySha256: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption;
  return proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEncryptionAlgorithm(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKeySha256(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEncryptionAlgorithm();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKeySha256();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string encryption_algorithm = 1;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.prototype.getEncryptionAlgorithm = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.prototype.setEncryptionAlgorithm = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string key_sha256 = 2;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.prototype.getKeySha256 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption.prototype.setKeySha256 = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string content_encoding = 1;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getContentEncoding = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setContentEncoding = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string content_disposition = 2;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getContentDisposition = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setContentDisposition = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string cache_control = 3;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getCacheControl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setCacheControl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string content_language = 5;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getContentLanguage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setContentLanguage = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 metageneration = 6;
 * @return {number}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getMetageneration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setMetageneration = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp time_deleted = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getTimeDeleted = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
*/
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setTimeDeleted = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.clearTimeDeleted = function() {
  return this.setTimeDeleted(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.hasTimeDeleted = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional string content_type = 8;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getContentType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setContentType = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int64 size = 9;
 * @return {number}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setSize = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional google.protobuf.Timestamp time_created = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getTimeCreated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
*/
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setTimeCreated = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.clearTimeCreated = function() {
  return this.setTimeCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.hasTimeCreated = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string crc32c = 11;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getCrc32c = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setCrc32c = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional int32 component_count = 12;
 * @return {number}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getComponentCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setComponentCount = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string md5_hash = 13;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getMd5Hash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setMd5Hash = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string etag = 14;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getEtag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setEtag = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional google.protobuf.Timestamp updated = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
*/
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setUpdated = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.clearUpdated = function() {
  return this.setUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.hasUpdated = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional string storage_class = 16;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getStorageClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setStorageClass = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string kms_key_name = 17;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getKmsKeyName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setKmsKeyName = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional google.protobuf.Timestamp time_storage_class_updated = 18;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getTimeStorageClassUpdated = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 18));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
*/
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setTimeStorageClassUpdated = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.clearTimeStorageClassUpdated = function() {
  return this.setTimeStorageClassUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.hasTimeStorageClassUpdated = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional bool temporary_hold = 19;
 * @return {boolean}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getTemporaryHold = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 19, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setTemporaryHold = function(value) {
  return jspb.Message.setProto3BooleanField(this, 19, value);
};


/**
 * optional google.protobuf.Timestamp retention_expiration_time = 20;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getRetentionExpirationTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 20));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
*/
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setRetentionExpirationTime = function(value) {
  return jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.clearRetentionExpirationTime = function() {
  return this.setRetentionExpirationTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.hasRetentionExpirationTime = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * map<string, string> metadata = 21;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getMetadataMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 21, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.clearMetadataMap = function() {
  this.getMetadataMap().clear();
  return this;};


/**
 * optional bool event_based_hold = 29;
 * @return {boolean}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getEventBasedHold = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 29, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setEventBasedHold = function(value) {
  return jspb.Message.setProto3BooleanField(this, 29, value);
};


/**
 * optional string name = 23;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 23, value);
};


/**
 * optional string id = 24;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 24, value);
};


/**
 * optional string bucket = 25;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getBucket = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 25, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setBucket = function(value) {
  return jspb.Message.setProto3StringField(this, 25, value);
};


/**
 * optional int64 generation = 26;
 * @return {number}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getGeneration = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 26, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setGeneration = function(value) {
  return jspb.Message.setProto3IntField(this, 26, value);
};


/**
 * optional CustomerEncryption customer_encryption = 28;
 * @return {?proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getCustomerEncryption = function() {
  return /** @type{?proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption} */ (
    jspb.Message.getWrapperField(this, proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption, 28));
};


/**
 * @param {?proto.google.events.cloud.storage.v1.StorageObjectData.CustomerEncryption|undefined} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
*/
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setCustomerEncryption = function(value) {
  return jspb.Message.setWrapperField(this, 28, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.clearCustomerEncryption = function() {
  return this.setCustomerEncryption(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.hasCustomerEncryption = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional string media_link = 100;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getMediaLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 100, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setMediaLink = function(value) {
  return jspb.Message.setProto3StringField(this, 100, value);
};


/**
 * optional string self_link = 101;
 * @return {string}
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.getSelfLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 101, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.events.cloud.storage.v1.StorageObjectData} returns this
 */
proto.google.events.cloud.storage.v1.StorageObjectData.prototype.setSelfLink = function(value) {
  return jspb.Message.setProto3StringField(this, 101, value);
};


goog.object.extend(exports, proto.google.events.cloud.storage.v1);
